setwd("blm-replicate")
source("packrat/init.R")
require(blmrep)
cat('\n\n\n\n\n\n\n\n')
cat(' ================================= ')
cat(' Welcome to blm replication package.')
cat(' Run source("inst/main.R") to replicate all results.')
cat(' Contact the authors in case of issues (lamadon@uchicago.edu).')
cat(' ================================= ')
cat('\n\n\n\n')
