setwd("blm-replicate")
source("packrat/init.R")
require(blmrep)

cat('\n\n\n\n\n\n\n\n')
cat(' ================================= \n')
cat(' Welcome to blm replication package.\n\n')
cat(' Run source("inst/main.R") to replicate all results.\n')
cat(' Contact the authors in case of issues (lamadon@uchicago.edu).\n')
cat(' ================================= \n')
cat('\n\n\n\n')
